# Generated by Django 5.1.7 on 2026-01-29 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
