# Generated by Django 5.1.7 on 2025-04-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_character_options_alter_follow_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="character",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
