# Generated by Django 5.1.7 on 2025-04-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_character_avatar_character_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="pfp/avatars"),
        ),
    ]
