# Generated by Django 5.1.7 on 2025-04-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_character_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
